### ISSUE TITLE
Fix Test Suites on Github Actions

### ISSUE THREAD

**Issue by aaron-contreras** [matestack/matestack-ui-bootstrap#27]
Following in line with matestack-ui-vuejs's GitHub Actions suite, the repo's current test suite is busted due to versioning of dependencies.

The test suite should be updated to cover

- Ruby 2.7-3.2.1
- Rails 6-7.0.4

**Comment by aaron-contreras** [comment]
@jonasjabari The fixed dependencies on #26 are required for this. I'll mark this as on-hold while the mentioned PR is reviewed and merged into the base branch.

I've already started working on [this branch](https://github.com/matestack/matestack-ui-bootstrap/tree/issue-27/fix-github-actions) and after a test with the Rails 7.0/Ruby 3.0 Dockerfile, the issue addressed on #26 seems to be happening on the CI as well :)

**Comment by jonasjabari** [comment]
Hey @aaron-contreras #26 is approved now :)
