### ISSUE TITLE
Run tests against multiple rails/ruby versions via GitHub actions as seen on matestack-ui-core

### ISSUE THREAD

**Issue by jonasjabari** [matestack/matestack-ui-bootstrap#8]

**Comment by aaron-contreras** [comment]
I'd like to work on this. Is it okay if I re-assign this to myself? @jonasjabari @keithrowell

**Comment by aaron-contreras** [comment]
Okay, so it looks like this is already a part of this repo and GitHub Actions is all set up. They seem to be a bit out-of-date just as the matestack-ui-vuejs ones were so I'll open up a new issue to address that and close this one since it's already a thing
